# .github/workflows/run_orgs.yml (deprecated)
name: DEPRECATED Org Targeter [WILL BE DELETED SOON]
# DEPRECATION NOTICE: This automation yielded minimal engagement returns
# Original purpose: Mass-follow target organizations to boost visibility
# Retired because:
# - Ineffective results
# - Minimal impact on stargazer growth
# - No significant increase in engagement or followers
# - Wasted GitHub Actions minutes

#on:
  # schedule:
    # - cron: '*/15 * * * *'    # every 15 minutes (UTC)
#  workflow_dispatch:          # allow manual trigger

jobs:
  run-orgs:
    name: Run Org Refollow Script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Run organization follow/refollow
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          python scripts/orgs.py
