# .github/workflows/run_autounstarback.yml
name: GitGrow UnstarBack (Scheduled)
# This workflow runs your autounstarback bot on a schedule.
# It is triggered four times per day and can also be run manually.
# It checks for users who have not reciprocated stars after 4 days and unstars them accordingly.
# The results are committed to the tracker-data branch and uploaded as an artifact.
#
# on:
#   schedule:
#     - cron: '20 3,11,19,5 * * *' # Fine for most users. If you expect >100 new stargazers per day, increase run frequency or set a stricter per-run limit to avoid stalls.
#   workflow_dispatch:

jobs:
  autounstarback:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main (code/scripts)
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Fetch state from tracker-data
        run: |
          git fetch origin tracker-data:tracker-data
          mkdir -p .github/state/
          git checkout tracker-data -- .github/state/ || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run autounstarback.py (unstar users who did not reciprocate after 4 days)
        run: python3 scripts/autounstarback.py
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
          BOT_USER: ${{ vars.BOT_USER }}

      - name: Commit and push stargazer state to tracker-data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: clean up unreciprocated growth stars [bot]"
          branch: tracker-data
          file_pattern: .github/state/stargazer_state.json

      - name: Upload stargazer state as artifact
        uses: actions/upload-artifact@v4
        with:
          name: stargazer-state
          path: .github/state/stargazer_state.json
